### PR TITLE
Migrate to the new Bookmarks API

### PR DESCRIPTION
**Pull request by yopox**
Bookmarks API was changed some time ago to merge Favorites and Bookmarks. As a result the plugin was not working and would soon become incompatible (2022.3+).

### CODE REVIEW

**Comment by boxed** [comment]
Why are all the files moved to java/? Githubs diff chokes on that. And are really all these gradle configs necessary? I honestly don't know! I haven't touched java since I wrote this... oh jesus. 9 years ago.

**Comment by yopox** [comment]
I applied the default project structure for IJ plugins using gradle. In fact I don't know how to build plugins the old way as we only have instructions using gradle (maybe it's not possible anymore when targeting a recent IJ platform version) :(
I also don't like gradle very much but it is at least very easy to try changes (`gradle runIde`) and build (`gradle buildPlugin`).

I guess what's important is that the plugin starts working again :
1. `bookmarkManager.getValidBookmarks()` is an old API and now returns an empty list so not a single action was working anymore
2. `bookmarkManager.addEditorBookmark` was removed so migration is required for binary compatibility

**Comment by boxed** [comment]
Is your username the same on plugins.jetbrains.com? So I can add you to the plugin and you can publish yourself

**Comment by yopox** [comment]
Yes my username is `yopox` on the marketplace.

**Pull request merged**
